// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dl/apis/procstore/procstore.proto

// ProcStore models the concrete types satisfying our ontology of process and state
// There is much care taken here to try and use the proto/go type system to ensure
// that all process entered is "valid". There are some additional checks/constraints
// on validity that cannot be expressed/ worth a complexity tradeoff, those located
// in dl/validator/
// The translation layer (to and from proto) is located in dl/dbtranslation

package procstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeKind int32

const (
	NodeKind_NK_UNSET    NodeKind = 0
	NodeKind_NK_EXECUTOR NodeKind = 1
	NodeKind_NK_OBJECT   NodeKind = 2
	NodeKind_NK_STEP     NodeKind = 3
	NodeKind_NK_PROCESS  NodeKind = 4
	NodeKind_NK_STATE    NodeKind = 5
	NodeKind_NK_WORKFLOW NodeKind = 6
	NodeKind_NK_PERSON   NodeKind = 7
)

var NodeKind_name = map[int32]string{
	0: "NK_UNSET",
	1: "NK_EXECUTOR",
	2: "NK_OBJECT",
	3: "NK_STEP",
	4: "NK_PROCESS",
	5: "NK_STATE",
	6: "NK_WORKFLOW",
	7: "NK_PERSON",
}

var NodeKind_value = map[string]int32{
	"NK_UNSET":    0,
	"NK_EXECUTOR": 1,
	"NK_OBJECT":   2,
	"NK_STEP":     3,
	"NK_PROCESS":  4,
	"NK_STATE":    5,
	"NK_WORKFLOW": 6,
	"NK_PERSON":   7,
}

func (x NodeKind) String() string {
	return proto.EnumName(NodeKind_name, int32(x))
}

func (NodeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0}
}

type Object_ObjectType int32

const (
	Object_OT_UNSET         Object_ObjectType = 0
	Object_OT_THING         Object_ObjectType = 1
	Object_OT_TOOL          Object_ObjectType = 2
	Object_OT_QUALIFICATION Object_ObjectType = 4
	Object_OT_EMPLOYEE      Object_ObjectType = 5
	Object_OT_MACHINE       Object_ObjectType = 6
)

var Object_ObjectType_name = map[int32]string{
	0: "OT_UNSET",
	1: "OT_THING",
	2: "OT_TOOL",
	4: "OT_QUALIFICATION",
	5: "OT_EMPLOYEE",
	6: "OT_MACHINE",
}

var Object_ObjectType_value = map[string]int32{
	"OT_UNSET":         0,
	"OT_THING":         1,
	"OT_TOOL":          2,
	"OT_QUALIFICATION": 4,
	"OT_EMPLOYEE":      5,
	"OT_MACHINE":       6,
}

func (x Object_ObjectType) String() string {
	return proto.EnumName(Object_ObjectType_name, int32(x))
}

func (Object_ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0, 0}
}

type Object struct {
	// Inherited Properties
	Uid         string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeKind    NodeKind          `protobuf:"varint,2,opt,name=node_kind,json=nodeKind,proto3,enum=procstore.NodeKind" json:"node_kind,omitempty"`
	ObjectType  Object_ObjectType `protobuf:"varint,3,opt,name=object_type,json=objectType,proto3,enum=procstore.Object_ObjectType" json:"object_type,omitempty"`
	HashId      string            `protobuf:"bytes,4,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	Name        string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to InstantiatedBy:
	//	*Object_Thing_
	//	*Object_Tool_
	//	*Object_Qualification_
	//	*Object_Employee_
	//	*Object_Machine_
	InstantiatedBy isObject_InstantiatedBy `protobuf_oneof:"instantiated_by"`
	// Relations...
	// Objects can exist_in 0, or 1 other objects
	ExistsIn *Object `protobuf:"bytes,10,opt,name=exists_in,json=existsIn,proto3" json:"exists_in,omitempty"`
	// Types that are valid to be assigned to State:
	//	*Object_IsIn
	//	*Object_IsNotIn
	State                isObject_State `protobuf_oneof:"state"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Object) GetNodeKind() NodeKind {
	if m != nil {
		return m.NodeKind
	}
	return NodeKind_NK_UNSET
}

func (m *Object) GetObjectType() Object_ObjectType {
	if m != nil {
		return m.ObjectType
	}
	return Object_OT_UNSET
}

func (m *Object) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type isObject_InstantiatedBy interface {
	isObject_InstantiatedBy()
}

type Object_Thing_ struct {
	Thing *Object_Thing `protobuf:"bytes,7,opt,name=thing,proto3,oneof"`
}

type Object_Tool_ struct {
	Tool *Object_Tool `protobuf:"bytes,8,opt,name=tool,proto3,oneof"`
}

type Object_Qualification_ struct {
	Qualification *Object_Qualification `protobuf:"bytes,9,opt,name=qualification,proto3,oneof"`
}

type Object_Employee_ struct {
	Employee *Object_Employee `protobuf:"bytes,13,opt,name=employee,proto3,oneof"`
}

type Object_Machine_ struct {
	Machine *Object_Machine `protobuf:"bytes,14,opt,name=machine,proto3,oneof"`
}

func (*Object_Thing_) isObject_InstantiatedBy() {}

func (*Object_Tool_) isObject_InstantiatedBy() {}

func (*Object_Qualification_) isObject_InstantiatedBy() {}

func (*Object_Employee_) isObject_InstantiatedBy() {}

func (*Object_Machine_) isObject_InstantiatedBy() {}

func (m *Object) GetInstantiatedBy() isObject_InstantiatedBy {
	if m != nil {
		return m.InstantiatedBy
	}
	return nil
}

func (m *Object) GetThing() *Object_Thing {
	if x, ok := m.GetInstantiatedBy().(*Object_Thing_); ok {
		return x.Thing
	}
	return nil
}

func (m *Object) GetTool() *Object_Tool {
	if x, ok := m.GetInstantiatedBy().(*Object_Tool_); ok {
		return x.Tool
	}
	return nil
}

func (m *Object) GetQualification() *Object_Qualification {
	if x, ok := m.GetInstantiatedBy().(*Object_Qualification_); ok {
		return x.Qualification
	}
	return nil
}

func (m *Object) GetEmployee() *Object_Employee {
	if x, ok := m.GetInstantiatedBy().(*Object_Employee_); ok {
		return x.Employee
	}
	return nil
}

func (m *Object) GetMachine() *Object_Machine {
	if x, ok := m.GetInstantiatedBy().(*Object_Machine_); ok {
		return x.Machine
	}
	return nil
}

func (m *Object) GetExistsIn() *Object {
	if m != nil {
		return m.ExistsIn
	}
	return nil
}

type isObject_State interface {
	isObject_State()
}

type Object_IsIn struct {
	IsIn *Object `protobuf:"bytes,11,opt,name=is_in,json=isIn,proto3,oneof"`
}

type Object_IsNotIn struct {
	IsNotIn *Object `protobuf:"bytes,12,opt,name=is_not_in,json=isNotIn,proto3,oneof"`
}

func (*Object_IsIn) isObject_State() {}

func (*Object_IsNotIn) isObject_State() {}

func (m *Object) GetState() isObject_State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Object) GetIsIn() *Object {
	if x, ok := m.GetState().(*Object_IsIn); ok {
		return x.IsIn
	}
	return nil
}

func (m *Object) GetIsNotIn() *Object {
	if x, ok := m.GetState().(*Object_IsNotIn); ok {
		return x.IsNotIn
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Object) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Object_Thing_)(nil),
		(*Object_Tool_)(nil),
		(*Object_Qualification_)(nil),
		(*Object_Employee_)(nil),
		(*Object_Machine_)(nil),
		(*Object_IsIn)(nil),
		(*Object_IsNotIn)(nil),
	}
}

// Subclasses of Object...
type Object_Thing struct {
	Props                map[string]string `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Object_Thing) Reset()         { *m = Object_Thing{} }
func (m *Object_Thing) String() string { return proto.CompactTextString(m) }
func (*Object_Thing) ProtoMessage()    {}
func (*Object_Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0, 0}
}

func (m *Object_Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Thing.Unmarshal(m, b)
}
func (m *Object_Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Thing.Marshal(b, m, deterministic)
}
func (m *Object_Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Thing.Merge(m, src)
}
func (m *Object_Thing) XXX_Size() int {
	return xxx_messageInfo_Object_Thing.Size(m)
}
func (m *Object_Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Thing proto.InternalMessageInfo

func (m *Object_Thing) GetProps() map[string]string {
	if m != nil {
		return m.Props
	}
	return nil
}

type Object_Tool struct {
	LoginPage            string   `protobuf:"bytes,1,opt,name=login_page,json=loginPage,proto3" json:"login_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object_Tool) Reset()         { *m = Object_Tool{} }
func (m *Object_Tool) String() string { return proto.CompactTextString(m) }
func (*Object_Tool) ProtoMessage()    {}
func (*Object_Tool) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0, 1}
}

func (m *Object_Tool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Tool.Unmarshal(m, b)
}
func (m *Object_Tool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Tool.Marshal(b, m, deterministic)
}
func (m *Object_Tool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Tool.Merge(m, src)
}
func (m *Object_Tool) XXX_Size() int {
	return xxx_messageInfo_Object_Tool.Size(m)
}
func (m *Object_Tool) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Tool.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Tool proto.InternalMessageInfo

func (m *Object_Tool) GetLoginPage() string {
	if m != nil {
		return m.LoginPage
	}
	return ""
}

type Object_Qualification struct {
	CertifiedBy          *Object  `protobuf:"bytes,1,opt,name=certified_by,json=certifiedBy,proto3" json:"certified_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object_Qualification) Reset()         { *m = Object_Qualification{} }
func (m *Object_Qualification) String() string { return proto.CompactTextString(m) }
func (*Object_Qualification) ProtoMessage()    {}
func (*Object_Qualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0, 2}
}

func (m *Object_Qualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Qualification.Unmarshal(m, b)
}
func (m *Object_Qualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Qualification.Marshal(b, m, deterministic)
}
func (m *Object_Qualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Qualification.Merge(m, src)
}
func (m *Object_Qualification) XXX_Size() int {
	return xxx_messageInfo_Object_Qualification.Size(m)
}
func (m *Object_Qualification) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Qualification.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Qualification proto.InternalMessageInfo

func (m *Object_Qualification) GetCertifiedBy() *Object {
	if m != nil {
		return m.CertifiedBy
	}
	return nil
}

type Object_Employee struct {
	RoleName             string    `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	CanBe                []*Person `protobuf:"bytes,2,rep,name=can_be,json=canBe,proto3" json:"can_be,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Object_Employee) Reset()         { *m = Object_Employee{} }
func (m *Object_Employee) String() string { return proto.CompactTextString(m) }
func (*Object_Employee) ProtoMessage()    {}
func (*Object_Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0, 3}
}

func (m *Object_Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Employee.Unmarshal(m, b)
}
func (m *Object_Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Employee.Marshal(b, m, deterministic)
}
func (m *Object_Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Employee.Merge(m, src)
}
func (m *Object_Employee) XXX_Size() int {
	return xxx_messageInfo_Object_Employee.Size(m)
}
func (m *Object_Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Employee proto.InternalMessageInfo

func (m *Object_Employee) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Object_Employee) GetCanBe() []*Person {
	if m != nil {
		return m.CanBe
	}
	return nil
}

type Object_Machine struct {
	ProgramName          string   `protobuf:"bytes,1,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object_Machine) Reset()         { *m = Object_Machine{} }
func (m *Object_Machine) String() string { return proto.CompactTextString(m) }
func (*Object_Machine) ProtoMessage()    {}
func (*Object_Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{0, 4}
}

func (m *Object_Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Machine.Unmarshal(m, b)
}
func (m *Object_Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Machine.Marshal(b, m, deterministic)
}
func (m *Object_Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Machine.Merge(m, src)
}
func (m *Object_Machine) XXX_Size() int {
	return xxx_messageInfo_Object_Machine.Size(m)
}
func (m *Object_Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Machine proto.InternalMessageInfo

func (m *Object_Machine) GetProgramName() string {
	if m != nil {
		return m.ProgramName
	}
	return ""
}

type Step struct {
	Uid         string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeKind    NodeKind `protobuf:"varint,2,opt,name=node_kind,json=nodeKind,proto3,enum=procstore.NodeKind" json:"node_kind,omitempty"`
	HashId      string   `protobuf:"bytes,3,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	ExecutedBy  *Object  `protobuf:"bytes,4,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	Causes      []*State `protobuf:"bytes,5,rep,name=causes,proto3" json:"causes,omitempty"`
	Requires    []*State `protobuf:"bytes,6,rep,name=requires,proto3" json:"requires,omitempty"`
	Name        string   `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to PrecededBy:
	//	*Step_PrecedingSteps
	//	*Step_PrecedingStep
	PrecededBy isStep_PrecededBy `protobuf_oneof:"preceded_by"`
	// Types that are valid to be assigned to FollowedBy:
	//	*Step_FollowingSteps
	//	*Step_FollowingStep
	FollowedBy           isStep_FollowedBy `protobuf_oneof:"followed_by"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{1}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Step) GetNodeKind() NodeKind {
	if m != nil {
		return m.NodeKind
	}
	return NodeKind_NK_UNSET
}

func (m *Step) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *Step) GetExecutedBy() *Object {
	if m != nil {
		return m.ExecutedBy
	}
	return nil
}

func (m *Step) GetCauses() []*State {
	if m != nil {
		return m.Causes
	}
	return nil
}

func (m *Step) GetRequires() []*State {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type isStep_PrecededBy interface {
	isStep_PrecededBy()
}

type Step_PrecedingSteps struct {
	PrecedingSteps *Step_Steps `protobuf:"bytes,7,opt,name=preceding_steps,json=precedingSteps,proto3,oneof"`
}

type Step_PrecedingStep struct {
	PrecedingStep *Step `protobuf:"bytes,8,opt,name=preceding_step,json=precedingStep,proto3,oneof"`
}

func (*Step_PrecedingSteps) isStep_PrecededBy() {}

func (*Step_PrecedingStep) isStep_PrecededBy() {}

func (m *Step) GetPrecededBy() isStep_PrecededBy {
	if m != nil {
		return m.PrecededBy
	}
	return nil
}

func (m *Step) GetPrecedingSteps() *Step_Steps {
	if x, ok := m.GetPrecededBy().(*Step_PrecedingSteps); ok {
		return x.PrecedingSteps
	}
	return nil
}

func (m *Step) GetPrecedingStep() *Step {
	if x, ok := m.GetPrecededBy().(*Step_PrecedingStep); ok {
		return x.PrecedingStep
	}
	return nil
}

type isStep_FollowedBy interface {
	isStep_FollowedBy()
}

type Step_FollowingSteps struct {
	FollowingSteps *Step_StepChoices `protobuf:"bytes,9,opt,name=following_steps,json=followingSteps,proto3,oneof"`
}

type Step_FollowingStep struct {
	FollowingStep *Step `protobuf:"bytes,10,opt,name=following_step,json=followingStep,proto3,oneof"`
}

func (*Step_FollowingSteps) isStep_FollowedBy() {}

func (*Step_FollowingStep) isStep_FollowedBy() {}

func (m *Step) GetFollowedBy() isStep_FollowedBy {
	if m != nil {
		return m.FollowedBy
	}
	return nil
}

func (m *Step) GetFollowingSteps() *Step_StepChoices {
	if x, ok := m.GetFollowedBy().(*Step_FollowingSteps); ok {
		return x.FollowingSteps
	}
	return nil
}

func (m *Step) GetFollowingStep() *Step {
	if x, ok := m.GetFollowedBy().(*Step_FollowingStep); ok {
		return x.FollowingStep
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Step) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Step_PrecedingSteps)(nil),
		(*Step_PrecedingStep)(nil),
		(*Step_FollowingSteps)(nil),
		(*Step_FollowingStep)(nil),
	}
}

type Step_StepChoices struct {
	Choice               []*Step_StepChoices_StepChoice `protobuf:"bytes,1,rep,name=choice,proto3" json:"choice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Step_StepChoices) Reset()         { *m = Step_StepChoices{} }
func (m *Step_StepChoices) String() string { return proto.CompactTextString(m) }
func (*Step_StepChoices) ProtoMessage()    {}
func (*Step_StepChoices) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{1, 0}
}

func (m *Step_StepChoices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step_StepChoices.Unmarshal(m, b)
}
func (m *Step_StepChoices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step_StepChoices.Marshal(b, m, deterministic)
}
func (m *Step_StepChoices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step_StepChoices.Merge(m, src)
}
func (m *Step_StepChoices) XXX_Size() int {
	return xxx_messageInfo_Step_StepChoices.Size(m)
}
func (m *Step_StepChoices) XXX_DiscardUnknown() {
	xxx_messageInfo_Step_StepChoices.DiscardUnknown(m)
}

var xxx_messageInfo_Step_StepChoices proto.InternalMessageInfo

func (m *Step_StepChoices) GetChoice() []*Step_StepChoices_StepChoice {
	if m != nil {
		return m.Choice
	}
	return nil
}

type Step_StepChoices_StepChoice struct {
	Choice               string   `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Step                 *Step    `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step_StepChoices_StepChoice) Reset()         { *m = Step_StepChoices_StepChoice{} }
func (m *Step_StepChoices_StepChoice) String() string { return proto.CompactTextString(m) }
func (*Step_StepChoices_StepChoice) ProtoMessage()    {}
func (*Step_StepChoices_StepChoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{1, 0, 0}
}

func (m *Step_StepChoices_StepChoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step_StepChoices_StepChoice.Unmarshal(m, b)
}
func (m *Step_StepChoices_StepChoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step_StepChoices_StepChoice.Marshal(b, m, deterministic)
}
func (m *Step_StepChoices_StepChoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step_StepChoices_StepChoice.Merge(m, src)
}
func (m *Step_StepChoices_StepChoice) XXX_Size() int {
	return xxx_messageInfo_Step_StepChoices_StepChoice.Size(m)
}
func (m *Step_StepChoices_StepChoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Step_StepChoices_StepChoice.DiscardUnknown(m)
}

var xxx_messageInfo_Step_StepChoices_StepChoice proto.InternalMessageInfo

func (m *Step_StepChoices_StepChoice) GetChoice() string {
	if m != nil {
		return m.Choice
	}
	return ""
}

func (m *Step_StepChoices_StepChoice) GetStep() *Step {
	if m != nil {
		return m.Step
	}
	return nil
}

type Step_Steps struct {
	Steps                []*Step  `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step_Steps) Reset()         { *m = Step_Steps{} }
func (m *Step_Steps) String() string { return proto.CompactTextString(m) }
func (*Step_Steps) ProtoMessage()    {}
func (*Step_Steps) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{1, 1}
}

func (m *Step_Steps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step_Steps.Unmarshal(m, b)
}
func (m *Step_Steps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step_Steps.Marshal(b, m, deterministic)
}
func (m *Step_Steps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step_Steps.Merge(m, src)
}
func (m *Step_Steps) XXX_Size() int {
	return xxx_messageInfo_Step_Steps.Size(m)
}
func (m *Step_Steps) XXX_DiscardUnknown() {
	xxx_messageInfo_Step_Steps.DiscardUnknown(m)
}

var xxx_messageInfo_Step_Steps proto.InternalMessageInfo

func (m *Step_Steps) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type Process struct {
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// An ID we assign that allows us to update a particular process.
	Guid        string   `protobuf:"bytes,7,opt,name=guid,proto3" json:"guid,omitempty"`
	NodeKind    NodeKind `protobuf:"varint,2,opt,name=node_kind,json=nodeKind,proto3,enum=procstore.NodeKind" json:"node_kind,omitempty"`
	HashId      string   `protobuf:"bytes,3,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	Name        string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Relations
	StartsWith           *Step    `protobuf:"bytes,6,opt,name=starts_with,json=startsWith,proto3" json:"starts_with,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{2}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Process) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Process) GetNodeKind() NodeKind {
	if m != nil {
		return m.NodeKind
	}
	return NodeKind_NK_UNSET
}

func (m *Process) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *Process) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Process) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Process) GetStartsWith() *Step {
	if m != nil {
		return m.StartsWith
	}
	return nil
}

// State lacks many shared fields because it is actually stored as a simple relationship
type State struct {
	// Relations
	Subject   *Object `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate string  `protobuf:"bytes,7,opt,name=predicate,proto3" json:"predicate,omitempty"`
	// Types that are valid to be assigned to Object:
	//	*State_StateName
	//	*State_StateObject
	Object               isState_Object `protobuf_oneof:"object"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{3}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetSubject() *Object {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *State) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

type isState_Object interface {
	isState_Object()
}

type State_StateName struct {
	StateName string `protobuf:"bytes,8,opt,name=state_name,json=stateName,proto3,oneof"`
}

type State_StateObject struct {
	StateObject *Object `protobuf:"bytes,9,opt,name=state_object,json=stateObject,proto3,oneof"`
}

func (*State_StateName) isState_Object() {}

func (*State_StateObject) isState_Object() {}

func (m *State) GetObject() isState_Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *State) GetStateName() string {
	if x, ok := m.GetObject().(*State_StateName); ok {
		return x.StateName
	}
	return ""
}

func (m *State) GetStateObject() *Object {
	if x, ok := m.GetObject().(*State_StateObject); ok {
		return x.StateObject
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*State) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*State_StateName)(nil),
		(*State_StateObject)(nil),
	}
}

type Workflow struct {
	Uid         string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeKind    NodeKind `protobuf:"varint,2,opt,name=node_kind,json=nodeKind,proto3,enum=procstore.NodeKind" json:"node_kind,omitempty"`
	HashId      string   `protobuf:"bytes,3,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	Name        string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Relations
	Contains             []*Process `protobuf:"bytes,6,rep,name=contains,proto3" json:"contains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Workflow) Reset()         { *m = Workflow{} }
func (m *Workflow) String() string { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()    {}
func (*Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{4}
}

func (m *Workflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow.Unmarshal(m, b)
}
func (m *Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow.Marshal(b, m, deterministic)
}
func (m *Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow.Merge(m, src)
}
func (m *Workflow) XXX_Size() int {
	return xxx_messageInfo_Workflow.Size(m)
}
func (m *Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow proto.InternalMessageInfo

func (m *Workflow) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Workflow) GetNodeKind() NodeKind {
	if m != nil {
		return m.NodeKind
	}
	return NodeKind_NK_UNSET
}

func (m *Workflow) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *Workflow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Workflow) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Workflow) GetContains() []*Process {
	if m != nil {
		return m.Contains
	}
	return nil
}

type Person struct {
	Uid      string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeKind NodeKind `protobuf:"varint,2,opt,name=node_kind,json=nodeKind,proto3,enum=procstore.NodeKind" json:"node_kind,omitempty"`
	HashId   string   `protobuf:"bytes,3,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	Name     string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// This must resolve to be a qualification object
	HasQualification     []*Object `protobuf:"bytes,4,rep,name=has_qualification,json=hasQualification,proto3" json:"has_qualification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{5}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Person) GetNodeKind() NodeKind {
	if m != nil {
		return m.NodeKind
	}
	return NodeKind_NK_UNSET
}

func (m *Person) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetHasQualification() []*Object {
	if m != nil {
		return m.HasQualification
	}
	return nil
}

// TODO(henry): figure out dgraph type imports
type Assigned struct {
	Uids                 map[string]string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Assigned) Reset()         { *m = Assigned{} }
func (m *Assigned) String() string { return proto.CompactTextString(m) }
func (*Assigned) ProtoMessage()    {}
func (*Assigned) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd6dbdbc3307e485, []int{6}
}

func (m *Assigned) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assigned.Unmarshal(m, b)
}
func (m *Assigned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assigned.Marshal(b, m, deterministic)
}
func (m *Assigned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assigned.Merge(m, src)
}
func (m *Assigned) XXX_Size() int {
	return xxx_messageInfo_Assigned.Size(m)
}
func (m *Assigned) XXX_DiscardUnknown() {
	xxx_messageInfo_Assigned.DiscardUnknown(m)
}

var xxx_messageInfo_Assigned proto.InternalMessageInfo

func (m *Assigned) GetUids() map[string]string {
	if m != nil {
		return m.Uids
	}
	return nil
}

func init() {
	proto.RegisterEnum("procstore.NodeKind", NodeKind_name, NodeKind_value)
	proto.RegisterEnum("procstore.Object_ObjectType", Object_ObjectType_name, Object_ObjectType_value)
	proto.RegisterType((*Object)(nil), "procstore.Object")
	proto.RegisterType((*Object_Thing)(nil), "procstore.Object.Thing")
	proto.RegisterMapType((map[string]string)(nil), "procstore.Object.Thing.PropsEntry")
	proto.RegisterType((*Object_Tool)(nil), "procstore.Object.Tool")
	proto.RegisterType((*Object_Qualification)(nil), "procstore.Object.Qualification")
	proto.RegisterType((*Object_Employee)(nil), "procstore.Object.Employee")
	proto.RegisterType((*Object_Machine)(nil), "procstore.Object.Machine")
	proto.RegisterType((*Step)(nil), "procstore.Step")
	proto.RegisterType((*Step_StepChoices)(nil), "procstore.Step.StepChoices")
	proto.RegisterType((*Step_StepChoices_StepChoice)(nil), "procstore.Step.StepChoices.StepChoice")
	proto.RegisterType((*Step_Steps)(nil), "procstore.Step.Steps")
	proto.RegisterType((*Process)(nil), "procstore.Process")
	proto.RegisterType((*State)(nil), "procstore.State")
	proto.RegisterType((*Workflow)(nil), "procstore.Workflow")
	proto.RegisterType((*Person)(nil), "procstore.Person")
	proto.RegisterType((*Assigned)(nil), "procstore.Assigned")
	proto.RegisterMapType((map[string]string)(nil), "procstore.Assigned.UidsEntry")
}

func init() {
	proto.RegisterFile("dl/apis/procstore/procstore.proto", fileDescriptor_cd6dbdbc3307e485)
}

var fileDescriptor_cd6dbdbc3307e485 = []byte{
	// 1270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdf, 0x6e, 0xdb, 0xb6,
	0x17, 0xb6, 0x12, 0xff, 0x91, 0x8e, 0xe2, 0x44, 0x65, 0xfb, 0x6b, 0xf5, 0x73, 0x5b, 0x34, 0xf3,
	0xd0, 0x2d, 0xd8, 0x0a, 0xa7, 0xcb, 0xfe, 0x05, 0x05, 0x56, 0x2c, 0x36, 0xd4, 0xda, 0x73, 0x6a,
	0xb9, 0xb2, 0x82, 0x6c, 0x57, 0x82, 0x22, 0x31, 0x36, 0x17, 0x47, 0x54, 0x45, 0xb9, 0xa9, 0xb1,
	0xcb, 0xdd, 0xee, 0x01, 0xf6, 0x22, 0xbb, 0xd8, 0x43, 0xec, 0x25, 0xf6, 0x0c, 0x7b, 0x80, 0x81,
	0xa4, 0x2c, 0xdb, 0xb5, 0x33, 0x60, 0x43, 0xb7, 0x9b, 0x84, 0x3c, 0xfa, 0xbe, 0xc3, 0x43, 0x9e,
	0xc3, 0xef, 0xd0, 0xf0, 0x61, 0x3c, 0xf6, 0xa7, 0x67, 0x94, 0x5e, 0xec, 0xfb, 0x31, 0x61, 0xfb,
	0x71, 0x42, 0x03, 0x96, 0xd2, 0x04, 0xcf, 0x47, 0x8d, 0x38, 0xa1, 0x29, 0x45, 0x5a, 0x6e, 0xa8,
	0xff, 0xa1, 0x42, 0xd9, 0x3e, 0xfb, 0x1e, 0x07, 0x29, 0x32, 0x60, 0x73, 0x42, 0x42, 0x53, 0xd9,
	0x55, 0xf6, 0x34, 0x87, 0x0f, 0xd1, 0x63, 0xd0, 0x22, 0x1a, 0x62, 0xef, 0x82, 0x44, 0xa1, 0xb9,
	0xb1, 0xab, 0xec, 0x6d, 0x1f, 0xdc, 0x6c, 0xcc, 0x9d, 0xf5, 0x68, 0x88, 0xbb, 0x24, 0x0a, 0x1d,
	0x35, 0xca, 0x46, 0xe8, 0x2b, 0xd0, 0xa9, 0xf0, 0xe6, 0xa5, 0xd3, 0x18, 0x9b, 0x9b, 0x82, 0x73,
	0x6f, 0x81, 0x23, 0xd7, 0xca, 0xfe, 0xb9, 0xd3, 0x18, 0x3b, 0x40, 0xf3, 0x31, 0xba, 0x03, 0x95,
	0x91, 0xcf, 0x46, 0x1e, 0x09, 0xcd, 0xa2, 0x08, 0xa3, 0xcc, 0xa7, 0x9d, 0x10, 0x21, 0x28, 0x46,
	0xfe, 0x25, 0x36, 0x4b, 0xc2, 0x2a, 0xc6, 0x68, 0x17, 0xf4, 0x10, 0xb3, 0x20, 0x21, 0x71, 0x4a,
	0x68, 0x64, 0x96, 0xc5, 0xa7, 0x45, 0x13, 0xda, 0x87, 0x52, 0x3a, 0x22, 0xd1, 0xd0, 0xac, 0xec,
	0x2a, 0x7b, 0xfa, 0xc1, 0x9d, 0xd5, 0x38, 0x5c, 0xfe, 0xb9, 0x5d, 0x70, 0x24, 0x0e, 0x3d, 0x82,
	0x62, 0x4a, 0xe9, 0xd8, 0x54, 0x05, 0xfe, 0xf6, 0x1a, 0x3c, 0xa5, 0xe3, 0x76, 0xc1, 0x11, 0x28,
	0xf4, 0x1c, 0xaa, 0xaf, 0x26, 0xfe, 0x98, 0x9c, 0x93, 0xc0, 0x17, 0x21, 0x68, 0x82, 0xf6, 0x60,
	0x95, 0xf6, 0x72, 0x11, 0xd6, 0x2e, 0x38, 0xcb, 0x3c, 0x74, 0x08, 0x2a, 0xbe, 0x8c, 0xc7, 0x74,
	0x8a, 0xb1, 0x59, 0x15, 0x3e, 0x6a, 0xab, 0x3e, 0xac, 0x0c, 0xd1, 0x2e, 0x38, 0x39, 0x1a, 0x7d,
	0x0e, 0x95, 0x4b, 0x3f, 0x18, 0x91, 0x08, 0x9b, 0xdb, 0x82, 0xf8, 0xff, 0x55, 0xe2, 0x0b, 0x09,
	0x68, 0x17, 0x9c, 0x19, 0x16, 0x35, 0x40, 0xc3, 0x6f, 0x08, 0x4b, 0x99, 0x47, 0x22, 0x13, 0x04,
	0xf1, 0xc6, 0x0a, 0xd1, 0x51, 0x25, 0xa6, 0x13, 0xa1, 0x3d, 0x28, 0x11, 0x81, 0xd5, 0xaf, 0xc1,
	0xb6, 0x15, 0xa7, 0x48, 0x38, 0x72, 0x1f, 0x34, 0xc2, 0xbc, 0x88, 0xa6, 0x1c, 0xbd, 0x75, 0x3d,
	0xba, 0x42, 0x58, 0x8f, 0xa6, 0x9d, 0xa8, 0xf6, 0x03, 0x94, 0x44, 0x12, 0xd0, 0x21, 0x94, 0xe2,
	0x84, 0xc6, 0xcc, 0x54, 0x76, 0x37, 0xf7, 0xf4, 0x83, 0xfa, 0x35, 0xc9, 0x6a, 0xf4, 0x39, 0xc8,
	0x8a, 0xd2, 0x64, 0xea, 0x48, 0x42, 0xed, 0x10, 0x60, 0x6e, 0xe4, 0x65, 0x7c, 0x81, 0xa7, 0xb3,
	0x32, 0xbe, 0xc0, 0x53, 0x74, 0x0b, 0x4a, 0xaf, 0xfd, 0xf1, 0x04, 0x8b, 0x12, 0xd6, 0x1c, 0x39,
	0x79, 0xb2, 0x71, 0xa8, 0xd4, 0x1e, 0x42, 0x91, 0x67, 0x14, 0xdd, 0x07, 0x18, 0xd3, 0x21, 0x89,
	0xbc, 0xd8, 0x1f, 0xe2, 0x8c, 0xaa, 0x09, 0x4b, 0xdf, 0x1f, 0xe2, 0x9a, 0x05, 0xd5, 0xa5, 0x0c,
	0xa2, 0xcf, 0x60, 0x2b, 0xc0, 0x49, 0x4a, 0xce, 0x09, 0x0e, 0xbd, 0x33, 0xb9, 0xd8, 0xda, 0x23,
	0xd4, 0x73, 0x58, 0x73, 0x5a, 0x7b, 0x09, 0xea, 0x2c, 0x89, 0xe8, 0x2e, 0x68, 0x09, 0x1d, 0x63,
	0x4f, 0x54, 0xb5, 0x5c, 0x50, 0xe5, 0x86, 0x1e, 0xaf, 0xec, 0x3d, 0x28, 0x07, 0x7e, 0xe4, 0x9d,
	0xf1, 0x88, 0x37, 0xdf, 0x72, 0xdc, 0xc7, 0x09, 0xa3, 0x91, 0x53, 0x0a, 0xfc, 0xa8, 0x89, 0x6b,
	0x8f, 0xa0, 0x92, 0xa5, 0x17, 0xbd, 0x07, 0x5b, 0x71, 0x42, 0x87, 0x89, 0x7f, 0xb9, 0xe8, 0x54,
	0xcf, 0x6c, 0xdc, 0x6f, 0x7d, 0x0c, 0x30, 0xbf, 0x78, 0x68, 0x0b, 0x54, 0xdb, 0xf5, 0x4e, 0x7a,
	0x03, 0xcb, 0x35, 0x0a, 0xd9, 0xcc, 0x6d, 0x77, 0x7a, 0xcf, 0x0d, 0x05, 0xe9, 0x50, 0xe1, 0x33,
	0xdb, 0x3e, 0x36, 0x36, 0xd0, 0x2d, 0x30, 0x6c, 0xd7, 0x7b, 0x79, 0x72, 0x74, 0xdc, 0x79, 0xd6,
	0x69, 0x1d, 0xb9, 0x1d, 0xbb, 0x67, 0x14, 0xd1, 0x0e, 0xe8, 0xb6, 0xeb, 0x59, 0x2f, 0xfa, 0xc7,
	0xf6, 0x77, 0x96, 0x65, 0x94, 0xd0, 0x36, 0x80, 0xed, 0x7a, 0x2f, 0x8e, 0x5a, 0xed, 0x4e, 0xcf,
	0x32, 0xca, 0xcd, 0x1b, 0xb0, 0x43, 0x22, 0x96, 0xfa, 0x51, 0x4a, 0xfc, 0x54, 0x9c, 0x53, 0xb3,
	0x02, 0x25, 0x96, 0xfa, 0x29, 0xae, 0xff, 0x54, 0x86, 0xe2, 0x20, 0xc5, 0xf1, 0x3b, 0x11, 0x9d,
	0x05, 0xd5, 0xd8, 0x5c, 0x52, 0x8d, 0x03, 0xd0, 0xf1, 0x1b, 0x1c, 0x4c, 0xe4, 0xea, 0x42, 0x52,
	0xd6, 0x66, 0x09, 0x66, 0xa8, 0xe6, 0x54, 0x9e, 0xfd, 0x84, 0x61, 0x66, 0x96, 0xc4, 0xd9, 0x1b,
	0x0b, 0xf0, 0x01, 0x8f, 0xdd, 0xc9, 0xbe, 0xa3, 0x47, 0xa0, 0x26, 0xf8, 0xd5, 0x84, 0x24, 0x98,
	0x99, 0xe5, 0x6b, 0xb0, 0x39, 0x22, 0x57, 0x30, 0xfd, 0x7a, 0x05, 0xdb, 0x5a, 0x55, 0xb0, 0xaf,
	0x61, 0x27, 0x4e, 0x70, 0x80, 0x43, 0x12, 0x0d, 0x3d, 0x96, 0xe2, 0x98, 0x65, 0x5a, 0xf6, 0xbf,
	0xa5, 0xa5, 0x70, 0x2c, 0xfe, 0xb0, 0x76, 0xc1, 0xd9, 0xce, 0xf1, 0xc2, 0x82, 0x0e, 0x61, 0x7b,
	0xd9, 0x43, 0x26, 0x6e, 0x3b, 0x6f, 0x39, 0xe0, 0xaa, 0xb4, 0x44, 0x45, 0xcf, 0x60, 0xe7, 0x9c,
	0x8e, 0xc7, 0xf4, 0x6a, 0xbe, 0xb6, 0x14, 0xb8, 0xbb, 0xeb, 0xd6, 0x6e, 0x8d, 0x28, 0x09, 0x30,
	0x6b, 0x2b, 0xce, 0x76, 0xce, 0xca, 0x23, 0x58, 0xf6, 0x93, 0x29, 0xce, 0x4a, 0x04, 0x8a, 0x53,
	0x5d, 0xa2, 0xd6, 0x7e, 0x56, 0x40, 0x5f, 0xf0, 0x8d, 0x9e, 0x42, 0x39, 0x10, 0xc3, 0x4c, 0x23,
	0x3e, 0xf8, 0x8b, 0x40, 0x16, 0xc6, 0x4e, 0xc6, 0xaa, 0x75, 0x00, 0xe6, 0x56, 0x74, 0x7b, 0xc1,
	0x9b, 0xa8, 0x1a, 0x39, 0x43, 0xef, 0x43, 0x51, 0x44, 0xb9, 0xb1, 0x36, 0x4a, 0x47, 0x7c, 0xac,
	0x35, 0xa0, 0x24, 0x77, 0xf7, 0x90, 0x97, 0x34, 0xce, 0x65, 0x6b, 0x05, 0x2e, 0xbf, 0x36, 0xab,
	0xa0, 0xcb, 0xd3, 0x95, 0x17, 0xa1, 0x0a, 0xba, 0xdc, 0xaa, 0x98, 0xd6, 0x7f, 0x57, 0xa0, 0xd2,
	0x4f, 0x68, 0x80, 0x19, 0x5b, 0x73, 0x23, 0x10, 0x14, 0x87, 0xdc, 0x54, 0x91, 0xa5, 0x33, 0x7c,
	0xc7, 0xb7, 0x64, 0x56, 0x99, 0xc5, 0xeb, 0x2b, 0xb3, 0xb4, 0x5a, 0x99, 0x8f, 0x41, 0x67, 0xa9,
	0x9f, 0xa4, 0xcc, 0xbb, 0x22, 0xe9, 0x48, 0x74, 0xdf, 0x35, 0xbb, 0x07, 0x89, 0x39, 0x25, 0xe9,
	0xa8, 0xfe, 0x8b, 0xc2, 0xcf, 0xcc, 0x4f, 0x31, 0xfa, 0x18, 0x2a, 0x6c, 0x22, 0xae, 0x5e, 0xc6,
	0x5b, 0x73, 0x27, 0x67, 0x08, 0x74, 0x0f, 0xb4, 0x38, 0xc1, 0x21, 0x97, 0x5e, 0x9c, 0x1d, 0xc1,
	0xdc, 0x80, 0x1e, 0x00, 0x08, 0x45, 0x91, 0x9a, 0xc7, 0x4b, 0x5b, 0x6b, 0x17, 0x1c, 0x4d, 0xd8,
	0x84, 0x96, 0x7e, 0x01, 0x5b, 0x12, 0x20, 0x9f, 0x19, 0x59, 0x09, 0xaf, 0xe9, 0x49, 0x05, 0x47,
	0x17, 0x40, 0x39, 0x6d, 0xaa, 0x50, 0x96, 0x8c, 0xfa, 0x6f, 0x0a, 0xa8, 0xa7, 0x34, 0xb9, 0x38,
	0x1f, 0xd3, 0xab, 0x7f, 0x57, 0xaf, 0xfe, 0x59, 0x26, 0x1a, 0xa0, 0x06, 0x34, 0x4a, 0x7d, 0x12,
	0xcd, 0x74, 0x08, 0x2d, 0xf6, 0x0b, 0x59, 0x56, 0x4e, 0x8e, 0xa9, 0xff, 0xaa, 0x40, 0x59, 0x76,
	0x91, 0xff, 0x66, 0x37, 0x8b, 0x6f, 0xb6, 0xa7, 0x70, 0x63, 0xe4, 0x33, 0x6f, 0xf9, 0xd9, 0x54,
	0x5c, 0x69, 0x72, 0x59, 0x0d, 0x18, 0x23, 0x9f, 0x2d, 0x35, 0xde, 0xfa, 0x6b, 0x50, 0x8f, 0x18,
	0x23, 0xc3, 0x08, 0x87, 0xe8, 0x13, 0x28, 0x4e, 0x48, 0x38, 0xbb, 0x78, 0xf7, 0x17, 0xe8, 0x33,
	0x48, 0xe3, 0x84, 0x84, 0xd9, 0x53, 0x41, 0x40, 0x6b, 0x5f, 0x82, 0x96, 0x9b, 0xfe, 0xce, 0x43,
	0xe1, 0xa3, 0x1f, 0x15, 0x50, 0x67, 0x7b, 0xe7, 0xad, 0xb2, 0xd7, 0xcd, 0x1b, 0xe7, 0x0e, 0xe8,
	0xbd, 0xae, 0x67, 0x7d, 0x6b, 0xb5, 0x4e, 0x5c, 0xdb, 0x31, 0x14, 0x54, 0x05, 0xad, 0xd7, 0xf5,
	0xec, 0xe6, 0x37, 0x56, 0xcb, 0x35, 0x36, 0x78, 0x2b, 0xed, 0x75, 0xbd, 0x81, 0x6b, 0xf5, 0x8d,
	0x4d, 0xde, 0x23, 0x7b, 0x5d, 0xaf, 0xef, 0xd8, 0x2d, 0x6b, 0x30, 0x30, 0x8a, 0x99, 0xab, 0x81,
	0x7b, 0xe4, 0xf2, 0x0e, 0x2a, 0x5d, 0x9d, 0xda, 0x4e, 0xf7, 0xd9, 0xb1, 0x7d, 0x6a, 0x94, 0x33,
	0x57, 0x7d, 0xcb, 0x19, 0xd8, 0x3d, 0xa3, 0x72, 0xf0, 0x1c, 0x34, 0x9e, 0xce, 0x01, 0xdf, 0x24,
	0x7a, 0x02, 0xd5, 0x56, 0x82, 0xfd, 0x14, 0xcf, 0x84, 0x63, 0x4d, 0xd6, 0x6b, 0x37, 0xd7, 0x9c,
	0x4a, 0xbd, 0x70, 0x56, 0x16, 0xbf, 0x03, 0x3e, 0xfd, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x3b,
	0x4c, 0xc1, 0x32, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProcStoreClient is the client API for ProcStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcStoreClient interface {
	CreateProcess(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Assigned, error)
}

type procStoreClient struct {
	cc *grpc.ClientConn
}

func NewProcStoreClient(cc *grpc.ClientConn) ProcStoreClient {
	return &procStoreClient{cc}
}

func (c *procStoreClient) CreateProcess(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Assigned, error) {
	out := new(Assigned)
	err := c.cc.Invoke(ctx, "/procstore.ProcStore/CreateProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcStoreServer is the server API for ProcStore service.
type ProcStoreServer interface {
	CreateProcess(context.Context, *Process) (*Assigned, error)
}

func RegisterProcStoreServer(s *grpc.Server, srv ProcStoreServer) {
	s.RegisterService(&_ProcStore_serviceDesc, srv)
}

func _ProcStore_CreateProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Process)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcStoreServer).CreateProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/procstore.ProcStore/CreateProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcStoreServer).CreateProcess(ctx, req.(*Process))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProcStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "procstore.ProcStore",
	HandlerType: (*ProcStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProcess",
			Handler:    _ProcStore_CreateProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dl/apis/procstore/procstore.proto",
}
