tech requirements per roles - this informs separation of duties & IT controls

what are the process requirements per role?

What processes is each system involved in?

what regulatory requirements apply to my hiring process?
* search all nodes in recruiting / Engineering, to see where control framework is not null

how much time am I spending on each candidate who makes it to the offer stage?
who's time is involved? how much time for each role? 
